### ISSUE TITLE
Caves Generation

### ISSUE THREAD

**Issue by 3Lord3** [PolyhedralDev/TerraDefaultConfig#13]
You obviously need to renew the caves. They have a few problems:
1) They look very artificial. It is as if they were created by hand, using a brush of spheres from WorldEdit. They are just drilled with spheres, it looks rough and ugly. In my opinion, it is worse than vanilla generation. You are very good at making biomes and landscape, but the caves are very weak.

2) Caves damage the surface of the world. They are adjacent to water bodies, so the water just flies, greatly worsening the impression of the landscape. 
And where caves appear correctly, they stand out with their monotony. There is such a variety of blocks and structures around, and here, it is as if several cryphers exploded. It is just a boring stone. Bushes, vines and earth could continue to grow in the caves that pass through the surface.
![image](https://user-images.githubusercontent.com/62335161/101196755-9776fe00-367a-11eb-93a8-4ea2a7c69ad7.png)
![image](https://user-images.githubusercontent.com/62335161/101197308-5f23ef80-367b-11eb-8931-61b7e2c03401.png)
![image](https://user-images.githubusercontent.com/62335161/101197687-e4a79f80-367b-11eb-8199-735dd2f9d6fb.png)

3) Lava. All over the world it appears strictly at level 8 and below, where space is not covered by blocks. Because of this, you don't have to look for lava, because you know which level to dig at to ensure that you can find it. Lava must appear randomly, at different levels. It must have its local level relative to the cave.
![image](https://user-images.githubusercontent.com/62335161/101196994-f3da1d80-367a-11eb-9302-0b976150aa71.png)

You probably know about the TerraformGenerator plugin. Caves and canyons are diverse and beautiful there. I would like to see something like that.

**Comment by dfsek** [comment]
This is more of a config issue, so I have transferred it to the config repository.

**Comment by TelepathicGrunt** [comment]
@3Lord3 geezus. FYI, if you want modders to be more receptive of your criticism, don’t try and word your reports like you just played the worst mod ever.

**Comment by solonovamax** [comment]
Going to add on to this a bit,
- caves could probably be a bit curvier.
- ravines should only generate down to y 8 in vanilla (or something similar), but not all the way down to y0.
- they're too smooth. needs more rng.

might do some testing on my own, and try to fix some of these

**Comment by dfsek** [comment]
@solonovamax @3Lord3 try out c787528d56a322f3e24a278dc026c740873dc605

(use latest Tectonic build of Terra)

I've implemented everything but ravine Y-level limitation. I think lava-filled ravines are cool, if you think otherwise it's as simple as changing a single value.

**Comment by solonovamax** [comment]
the y level limitation just makes them slightly less likely to happen & makes them less deep when they _do_ happen. I just have an issue with the 8 block deep of lava ravines, as in normal vanilla it's like 2-3 blocks at most iirc.

**Comment by solonovamax** [comment]
Also about number 3,
it would be pretty cool if we had local liquid levels...

**Comment by dfsek** [comment]
Local levels are completely do-able with our current system. There's just nowhere they'd really work well.

**Comment by solonovamax** [comment]
we could try and replicate the caves mojang showed off at minecon, idk

**Comment by 3Lord3** [comment]
> @3Lord3 geezus. FYI, if you want modders to be more receptive of your criticism, don’t try and word your reports like you just played the worst mod ever.

Excuse me. I use a translator and try to write in a way that a translator can clearly translate my idea.

**Comment by dfsek** [comment]
Several cave changes implemented in v2's default config
