### ISSUE TITLE
Mushroom structures can join together

### ISSUE THREAD

**Issue by Roan-V** [PolyhedralDev/TerraDefaultConfig#29]
The mushroom structures in the mushroom island can join together: 
![image](https://user-images.githubusercontent.com/77012724/107262448-db063380-6a40-11eb-8f17-f9e5d6610bba.png)

It's also possible for them to spawn really tall, possible the same joining issue but this time vertical?
![image](https://user-images.githubusercontent.com/77012724/107262558-fb35f280-6a40-11eb-84f2-3ff51565e701.png)

**Comment by dfsek** [comment]
We actually just use Vanilla mushroom generation. I suppose we could replace them with custom structures if this is an issue

**Comment by dfsek** [comment]
Closing since this is Vanilla behavior,
