### ISSUE TITLE
Failed to Load Plugin

### ISSUE THREAD

**Issue by Nexobeast** [PolyhedralDev/TerraDefaultConfig#40]
Hi
Error is found here: "https://pastebin.com/XZzwa8FH"
I use Paper 1.14.4 and all files got all Permissions they need.

Thanks,
Nexo

**Comment by solonovamax** [comment]
@dfsek you have to move this to the Terra repo because I can't.

Also @Nexobeast:
the issue is you're trying to load a pack which contains blocks that don't exist in 1.14 lol

**Comment by Nexobeast** [comment]
"the issue is you're trying to load a pack which contains blocks that don't exist in 1.14 lol"
Excatly, but the Legacy-Version is for 1.13.1-1.15.2, and dont work on 1.14.4

**Comment by solonovamax** [comment]
1. We don't support the legacy versions. If you want it to work with legacy, you'll have to modify the pack.
2. I don't even think the legacy pack works tbh
