### ISSUE TITLE
Could not parse data: minecraft:grass_path

### ISSUE THREAD

**Issue by dillfrescott** [PolyhedralDev/TerraDefaultConfig#61]
https://gist.github.com/DillFrescott/35916404594ff71b80f828bb8608d29d

Here is the full "latest.log" of the error. Its the newest version of Terra running on the newest version of Spigot.

**Comment by dillfrescott** [comment]
?

**Comment by dfsek** [comment]
Use the latest default config. You obviously cannot use the 1.16 default config on 1.17.

**Comment by dillfrescott** [comment]
@dfsek oh. Im dumb lol
