### ISSUE TITLE
Some Vanilla structures doesn't have spawned entities

### ISSUE THREAD

**Issue by REALMWTH** [PolyhedralDev/TerraDefaultConfig#65]
Pillagers and Golems aren't spawned near outposts.
Elder Guardians and Guardians aren't spawned near monuments.
Also Witches and Black cats aren't spawned in Swamp Huts.

Two more issues:
1) Ocean Ruins arent's spawning at all
2) /locate village command doesn't find villages even if they are actually generated

**Comment by Sancires** [comment]
This is not related to the default config, and is a [duplicate issue](https://github.com/PolyhedralDev/Terra/issues/111).

**Comment by Sancires** [comment]
Additionally:

- Ocean Ruins are not apart of the default pack.
- Do not use `/locate`. Use `/te structure locate`
